language: cpp
os:
  - linux
  - osx
  - windows
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        choco install cmake
        choco install make
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
install:
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then
    sudo apt-get update;
    sudo apt-get -y install libpthread-stubs0-dev;
    sudo apt-get -y install libgl1-mesa-dev;
    sudo apt-get -y install libxrandr-dev;
    sudo apt-get -y install libfreetype6-dev;
    sudo apt-get -y install libglew1.5-dev;
    sudo apt-get -y install libjpeg8-dev;
    sudo apt-get -y install libsndfile1-dev;
    sudo apt-get -y install libopenal-dev;
    sudo apt-get -y install libx11-dev;
    sudo apt-get -y install xorg-dev;
    sudo apt-get -y install freeglut3-dev;
    sudo apt-get -y install libudev-dev; 
    sudo apt-get purge cmake;
    CMAKE_URL="https://cmake.org/files/v3.19/cmake-3.19.0-Linux-x86_64.tar.gz";
    mkdir cmake && wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake;
    sudo apt-get -y upgrade;
    sudo apt-get -y dist-upgrade; fi
before_script:
- mkdir build; cd build;
- if [ $TRAVIS_OS_NAME = 'linux' ]; then ../cmake/bin/cmake .. ; fi
- if [ $TRAVIS_OS_NAME = 'osx' ]; then cmake .. ; fi
- |-
    case $TRAVIS_OS_NAME in
      windows)
        cmake -G "Unix Makefiles" ..
        ;;
    esac
    
script:
  - make