language: cpp
os:
  - linux
  - osx
  - windows
dist:
  - bionic
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install mingw
        choco install cmake
        choco install make
        ;;
    esac
install:
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then
    sudo apt-get update;
    sudo apt-get -y install libsfml-dev; 
    cd ..;
    CMAKE_URL="https://cmake.org/files/v3.19/cmake-3.19.0-Linux-x86_64.tar.gz";
    mkdir cmake && wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake;
    cd mcpp;fi
before_script:
- mkdir build; cd build;
- if [ $TRAVIS_OS_NAME = 'linux' ]; then ../../cmake/bin/cmake .. ; fi
- if [ $TRAVIS_OS_NAME = 'osx' ]; then cmake .. ; fi
- |-
    case $TRAVIS_OS_NAME in
      windows)
        cmake -G "Unix Makefiles" ..
        ;;
    esac
script:
  - make