image: 
  - Ubuntu
configuration:
  - Release
  - Debug
install:
  - sh: sudo apt-get install libx11-dev
  - sh: sudo apt-get install xorg-dev
  - sh: sudo apt-get install freeglut3-dev
  - sh: sudo apt-get install libudev-dev


before_build:
  - mkdir -p build; cd build; cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..

build_script:
  - make